### ISSUE TITLE
UMP ERROR FFMPEG

### ISSUE THREAD

**Issue by 0XOPx** [Chen-Wenru/Ultralight-MIDIPlayer#1]
Error Report:
                 --- UMP ERROR REPORT ---
Something went wrong
Unexpected problem occurred in Video Render. Make sure your ffmpeg executable is correct.

>> STACK TRACE
java.io.IOException: Potok został zakończony
  at java.io.FileOutputStream.writeBytes(Native Method)
  at java.io.FileOutputStream.write(Unknown Source)
  at java.io.BufferedOutputStream.write(Unknown Source)
  at java.io.FilterOutputStream.write(Unknown Source)
  at pipira.MIDIPlayer.app.converter.MIDIConverter.run(MIDIConverter.java:181)
  at pipira.MIDIPlayer.app.converter.MIDIConverterApp.lambda$0(MIDIConverterApp.java:168)
  at java.lang.Thread.run(Unknown Source)

>> DEBUG INFORMATION
Application:
  Version:      1.6.2
  Language:     English
  MIDI Device:  OmniMIDI 0.6
  Resourcepack: Synthesia Note Colors 1.1.1 by PipiraMine (format 0, FORGED)
  Time:         1729529074672 (Mon Oct 21 18:44:34 CEST 2024)
System:
  OS:       Windows 10 amd64 10.0
  Java:     1.8.0_421
  JVM:      Java HotSpot(TM) 64-Bit Server VM 25.421-b09
  JVM Args: 
Config:
  version: 2
  language: en
  midi:
    loaderThreads: 0
    loadNotesOnly: false
    usePlayThread: true
    synth: OmniMIDI
  render:
    background: 0xc0c0c0
    font: Segoe UI
    fpsLimit: 120
    height: 996
    renderInterval: 0.1
    resourcePack: Synthesia Pack.zip
    usePFAColors: false
    width: 1920
    overlay:
      opaque: false
      info:
        scale: 1.0
        type: DEFAULT
        position: TOP_RIGHT
        showDuration: false
      fps:
        type: SHOW_ALL
      desync:
        type: SHOW_ALL
      loading:
        showMemoryUsage: true
  ui:
    font: Yu Gothic UI
  files:
    midi: C:\Users\natal\Downloads\HAHA Song Remastet.mid
    ffmpeg: D:\Users\natal\Zeinth Modded\Release-64\ffmpeg.exe
    resourcePacks: null
  updateChecker:
    checkOnStartup: true
    branch: development
Renderer:
  Class:        pipira.MIDIPlayer.render.renderer.DefaultMIDIRenderer
  Running:      false
  Sequence:     HAHA Song Remastet
  Time:         1552609703100
  Time Started: 1409116102400
  Resolution:   1920x996
  FPS Limit:    120 (8.333333333333334ms)
  Speed:        1.0
  Interval:     0.1
               --- END UMP ERROR REPORT ---

(u used yamaha c7 and omni midi not official texturepack btw)

**Comment by 0XOPx** [comment]
c

**Comment by lastata** [comment]
if there are any problems, just telling you that this guy is not a dev. go to https://pipiraworld.web.fc2.com/ump/en.html
it is the site of the official developer
